[package]
name = "infer"
version = "0.1.0"
authors = ["Bojan <dbojan@gmail.com>"]
edition = "2018"
description = "Small crate to infer file types based on its magic number signature"
license = "MIT"
keywords = ["magic-number", "magic-number", "filetype", "file", "mime", "mime-types", "binary"]
readme = "README.md"
homepage = "https://github.com/bojand/infer"
repository = "https://github.com/bojand/infer"
documentation = "https://github.com/bojand/infer"

[dependencies]
byteorder = "1"